version: "3.7"

services:
  metacareapidb:
    image: postgres
    restart: always
    container_name: metacareapidb
    networks:
      - metacareapi-network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=metacareapidb
    ports:
      - "5438:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  metacareapi:
    image: 12ci013590/metacareapi:4
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: metacareapi
    restart: always
    # volumes:
    #   - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - metacareapidb
    # environment:
    #   - MONGODB_URI=mongodb://node-react-starter-db/node-react-starter-db
    networks:
      - metacareapi-network
volumes:
  metacareapidb:
    name: metacareapidb

networks:
  metacareapi-network:
    name: metacareapi-network
